%% Independent MATLAB verification of the Franka Pinocchio model
% Robotics System Toolbox independently recomputes:
%   FK, Jacobian, M(q), velocity-product torque, gravity, inverse dynamics.

clear;
clc;

script_dir = fileparts(mfilename('fullpath'));
repo_root = fileparts(script_dir);

reference_csv = fullfile( ...
    repo_root, ...
    'artifacts', ...
    'phase4_matlab_verification', ...
    'pinocchio_reference.csv' ...
);

urdf_path = fullfile( ...
    repo_root, ...
    'urdfs', ...
    'official_franka', ...
    'fer.urdf' ...
);

output_dir = fullfile( ...
    repo_root, ...
    'artifacts', ...
    'phase4_matlab_verification' ...
);

fprintf('Phase 4 MATLAB Verification\n');
fprintf('===========================\n');
fprintf('URDF: %s\n', urdf_path);
fprintf('Reference: %s\n\n', reference_csv);

%% Load independent MATLAB robot model

robot = importrobot( ...
    urdf_path, ...
    'DataFormat', 'row' ...
);

robot.Gravity = [0 0 -9.81];

tool_frame = 'fer_link8';

fprintf('MATLAB robot DOF: %d\n', numel(homeConfiguration(robot)));
fprintf('Tool frame: %s\n\n', tool_frame);

%% Load Pinocchio reference data

data = readtable( ...
    reference_csv, ...
    'VariableNamingRule', 'preserve' ...
);

num_states = height(data);

position_error_m = zeros(num_states, 1);
rotation_error_rad = zeros(num_states, 1);
jacobian_error = zeros(num_states, 1);
mass_matrix_error = zeros(num_states, 1);
velocity_product_error_nm = zeros(num_states, 1);
gravity_error_nm = zeros(num_states, 1);
inverse_dynamics_error_nm = zeros(num_states, 1);

for k = 1:num_states

    %% State

    q = zeros(1, 7);
    dq = zeros(1, 7);
    ddq = zeros(1, 7);

    for j = 1:7
        q(j) = data{k, sprintf('q%d', j)};
        dq(j) = data{k, sprintf('dq%d', j)};
        ddq(j) = data{k, sprintf('ddq%d', j)};
    end

    %% Pinocchio FK reference

    p_ref = zeros(3, 1);

    for r = 1:3
        p_ref(r) = data{k, sprintf('tool_position_%d', r)};
    end

    R_ref = zeros(3, 3);

    for r = 1:3
        for c = 1:3
            R_ref(r,c) = data{k, sprintf( ...
                'tool_rotation_%d_%d', r, c ...
            )};
        end
    end

    %% MATLAB FK

    T_matlab = getTransform(robot, q, tool_frame);

    R_matlab = T_matlab(1:3, 1:3);
    p_matlab = T_matlab(1:3, 4);

    position_error_m(k) = norm(p_matlab - p_ref);

    R_error = R_matlab * R_ref';

    cos_angle = (trace(R_error) - 1.0) / 2.0;
    cos_angle = max(-1.0, min(1.0, cos_angle));

    rotation_error_rad(k) = acos(cos_angle);

    %% Jacobian

    J_ref = zeros(6, 7);

    for r = 1:6
        for c = 1:7
            J_ref(r,c) = data{k, sprintf( ...
                'jacobian_%d_%d', r, c ...
            )};
        end
    end

    % MATLAB geometricJacobian ordering:
    %   [angular; linear]
    %
    % Pinocchio project ordering:
    %   [linear; angular]
    %
    % Reorder MATLAB before comparison.
    J_raw = geometricJacobian( ...
        robot, ...
        q, ...
        tool_frame ...
    );

    J_matlab = [
        J_raw(4:6, :);
        J_raw(1:3, :)
    ];

    jacobian_error(k) = norm( ...
        J_matlab - J_ref, ...
        'fro' ...
    );

    %% Mass matrix

    M_ref = zeros(7, 7);

    for r = 1:7
        for c = 1:7
            M_ref(r,c) = data{k, sprintf( ...
                'mass_matrix_%d_%d', r, c ...
            )};
        end
    end

    M_matlab = massMatrix(robot, q);

    mass_matrix_error(k) = norm( ...
        M_matlab - M_ref, ...
        'fro' ...
    );

    %% Velocity-product torque C(q,dq)dq

    velocity_ref = zeros(1, 7);

    for j = 1:7
        velocity_ref(j) = data{k, sprintf( ...
            'velocity_product_%d', j ...
        )};
    end

    velocity_matlab = velocityProduct( ...
        robot, ...
        q, ...
        dq ...
    );

    velocity_product_error_nm(k) = norm( ...
        velocity_matlab - velocity_ref ...
    );

    %% Gravity

    gravity_ref = zeros(1, 7);

    for j = 1:7
        gravity_ref(j) = data{k, sprintf( ...
            'gravity_%d', j ...
        )};
    end

    gravity_matlab = gravityTorque(robot, q);

    gravity_error_nm(k) = norm( ...
        gravity_matlab - gravity_ref ...
    );

    %% Inverse dynamics

    tau_ref = zeros(1, 7);

    for j = 1:7
        tau_ref(j) = data{k, sprintf( ...
            'tau_rnea_%d', j ...
        )};
    end

    tau_matlab = inverseDynamics( ...
        robot, ...
        q, ...
        dq, ...
        ddq ...
    );

    inverse_dynamics_error_nm(k) = norm( ...
        tau_matlab - tau_ref ...
    );

end

%% Results table

results = table( ...
    data.state_id, ...
    position_error_m, ...
    rotation_error_rad, ...
    jacobian_error, ...
    mass_matrix_error, ...
    velocity_product_error_nm, ...
    gravity_error_nm, ...
    inverse_dynamics_error_nm, ...
    'VariableNames', { ...
        'state_id', ...
        'position_error_m', ...
        'rotation_error_rad', ...
        'jacobian_fro_error', ...
        'mass_matrix_fro_error', ...
        'velocity_product_error_nm', ...
        'gravity_error_nm', ...
        'inverse_dynamics_error_nm' ...
    } ...
);

results_csv = fullfile( ...
    output_dir, ...
    'matlab_verification_results.csv' ...
);

writetable(results, results_csv);

%% Summary

fprintf('Verification states: %d\n\n', num_states);

fprintf( ...
    'Max FK position error:       %.6e m\n', ...
    max(position_error_m) ...
);

fprintf( ...
    'Max FK rotation error:       %.6e rad\n', ...
    max(rotation_error_rad) ...
);

fprintf( ...
    'Max Jacobian Fro error:      %.6e\n', ...
    max(jacobian_error) ...
);

fprintf( ...
    'Max mass matrix Fro error:   %.6e\n', ...
    max(mass_matrix_error) ...
);

fprintf( ...
    'Max velocity-product error:  %.6e N*m\n', ...
    max(velocity_product_error_nm) ...
);

fprintf( ...
    'Max gravity error:           %.6e N*m\n', ...
    max(gravity_error_nm) ...
);

fprintf( ...
    'Max inverse dynamics error:  %.6e N*m\n', ...
    max(inverse_dynamics_error_nm) ...
);

fprintf('\nResults: %s\n', results_csv);

summary = struct();

summary.number_of_states = num_states;

summary.max_fk_position_error_m = ...
    max(position_error_m);

summary.max_fk_rotation_error_rad = ...
    max(rotation_error_rad);

summary.max_jacobian_fro_error = ...
    max(jacobian_error);

summary.max_mass_matrix_fro_error = ...
    max(mass_matrix_error);

summary.max_velocity_product_error_nm = ...
    max(velocity_product_error_nm);

summary.max_gravity_error_nm = ...
    max(gravity_error_nm);

summary.max_inverse_dynamics_error_nm = ...
    max(inverse_dynamics_error_nm);

summary_path = fullfile( ...
    output_dir, ...
    'matlab_verification_summary.json' ...
);

fid = fopen(summary_path, 'w');

fprintf( ...
    fid, ...
    '%s', ...
    jsonencode(summary, PrettyPrint=true) ...
);

fclose(fid);

fprintf('Summary: %s\n', summary_path);

